export const centerList = [
  {
    id: "01",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "02",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "03",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "04",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "02",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "03",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "04",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "02",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "03",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "04",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "02",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "03",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "04",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "02",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "03",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "04",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "02",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "03",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "04",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "02",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "03",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "04",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "02",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "03",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
  {
    id: "04",
    name: "cbe govt hospital",
    latitute: "123",
    longitute: "321",
  },
];
